# Generated by Django 2.2.12 on 2020-04-25 13:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivatedPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affectedResource', models.CharField(max_length=200)),
                ('metadata', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('actionItem', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('resourceTagToNotify', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affectedResources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceName', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isChecked', models.BooleanField(default=False)),
                ('isFixed', models.BooleanField(default=False)),
                ('fixedDate', models.DateTimeField(default=None, null=True)),
                ('connectedPolicy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudinis.ActivatedPolicy')),
            ],
        ),
        migrations.AddField(
            model_name='activatedpolicy',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudinis.Policy'),
        ),
    ]
