# Generated by Django 2.2.12 on 2020-06-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudiniuser',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cloudinis.Organization'),
        ),
    ]
