# Generated by Django 2.2.12 on 2020-07-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedpolicy',
            name='resourceTagToNotify',
            field=models.CharField(max_length=200, verbose_name='Tag to enforce'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='affectedResources',
            field=models.CharField(max_length=200),
        ),
    ]
