# Generated by Django 3.0.8 on 2020-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='fixedDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
