# Generated by Django 2.2.12 on 2020-07-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_scan_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
