# Generated by Django 2.2.12 on 2020-04-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudiniuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
