# Generated by Django 2.2.12 on 2020-04-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0002_auto_20200422_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudiniuser',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cloudinis.Organization'),
        ),
    ]
