# Generated by Django 3.0.8 on 2020-07-25 11:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudinis', '0002_violation_fixeddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activatedpolicy',
            name='actionItem',
            field=models.CharField(choices=[('None', 'None'), ('Notify', 'Notify'), ('Delete', 'Delete')], max_length=200, verbose_name='Action item'),
        ),
        migrations.AlterField(
            model_name='activatedpolicy',
            name='resourceTagToNotify',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None, verbose_name='Tag to notify'),
        ),
    ]
