# Generated by Django 3.0.5 on 2020-05-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudiniuser',
            name='access_key',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudiniuser',
            name='secret_key',
            field=models.CharField(default='123', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudiniuser',
            name='session_token',
            field=models.CharField(default='123', max_length=400),
            preserve_default=False,
        ),
    ]
